### ISSUE TITLE
SVD on cross-identification matrix

### ISSUE THREAD

**Issue by MatthewJA** [MatthewJA/lairs#23]
Generate the cross-identification matrix and do SVD to get FIRST/WISE features.

**Comment by MatthewJA** [comment]
Well, the SVD isn't super interesting. It's pretty sparse itself.

**Comment by chengsoonong** [comment]
Sparse SVD vectors are **very** interesting. Usually the problem is that the singular vectors are dense, which means that when you reconstruct the matrix the resulting matrix is dense. This violates the requirement that you have that the original data is sparse.

**Comment by MatthewJA** [comment]
Any suggestions for what I ought to do with this knowledge? I'm not really sure I understand SVD deeply enough to know what's going on.
