### ISSUE TITLE
Read Aditya's ISML2018 guest lecture slides

### ISSUE THREAD

**Issue by MatthewJA** [MatthewJA/lairs#26]
https://machlearn.gitlab.io/isml2018/lectures/12a_Guest_Menon.pdf

These discuss classification and recommendation, which is essentially cross-identification. I should read these.

They also talk about binary classification in a really good way and it would be useful to incorporate some of this into my own vocabulary. Just in case I need to write something at some point.

**Comment by chengsoonong** [comment]
Aditya.Menon@anu.edu.au is around for only a little while longer. So I suggest that you pick his brain as soon as you have any questions.
