### ISSUE TITLE
Obtain reduced cosmology fields from Pawsey

### ISSUE THREAD

**Issue by MatthewJA** [MatthewJA/lairs#34]
Naomi to complete; or I can do it if I get access to Pawsey. They are ~100 GB each.

Determine which fields they are, using the small maps. (I can do this bit)

**Comment by naomimg** [comment]
[2018_miyazaki_heald.pdf](https://github.com/MatthewJA/lairs/files/2071079/2018_miyazaki_heald.pdf)

List of ASKAP fields reduced, how to get Pawsey account and how to access data!

**Comment by MatthewJA** [comment]
Fantastic, thanks!

**Comment by MatthewJA** [comment]
CDFS is +3h, ELAIS-S1 is at 0h. But these might be cosmology fields; it's hard to tell. Is there a list of cosmology fields or just that map?
